name: Feature Request
description: Any features (or mods) that you would like to see added to Modpack Frenzy
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the base engine?
    validations:
      required: true
