name: Mod Request
description: Submit any mods you would like to see added. 
labels: [addition]
body:
- type: input
  id: request
      label: Mod Request
      description: "What mods do you want to see added into the Modpack Frenzy?"
      required: true
